// scripts/insert-events.mjs
// 驗證並批次 INSERT 探索事件到 Supabase events 表
// 執行：node scripts/insert-events.mjs

import pg from 'pg';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

// ── 必填欄位驗證 ─────────────────────────────────────────────────
const REQUIRED = [
  'base_type', 'tier', 'attribute', 'hidden_level',
  'total_layers', 'progression', 'outcome_weights',
  'action_modifiers', 'base_rare_rate',
];

function validate(event, index) {
  const missing = REQUIRED.filter(f => event[f] === undefined || event[f] === null);
  if (missing.length > 0) return `第 ${index + 1} 條缺少欄位：${missing.join(', ')}`;
  if (![1, 2, 3, 4, 5].includes(event.tier)) return `第 ${index + 1} 條 tier 值無效：${event.tier}`;
  if (!['fire', 'water', 'wood', 'metal', 'earth'].includes(event.attribute)) return `第 ${index + 1} 條 attribute 值無效：${event.attribute}`;
  if (event.total_layers < 1 || event.total_layers > 6) return `第 ${index + 1} 條 total_layers 超出範圍：${event.total_layers}`;
  const layerKeys = Object.keys(event.progression);
  if (layerKeys.length !== event.total_layers) return `第 ${index + 1} 條 progression 層數（${layerKeys.length}）與 total_layers（${event.total_layers}）不符`;
  return null;
}

// ── 事件資料 ──────────────────────────────────────────────────────
const EVENTS = [
  {"base_type":"unknown","sub_types":["monster","resource","nothing"],"tier":1,"attribute":"wood","hidden_level":12,"total_layers":2,"progression":{"L1":{"text":"林間草木搖動，風向突然轉變，帶來一絲異味。","best_action":"wait"},"L2":{"text":"地面有新鮮踩踏痕跡，泥土翻動不久。","best_action":"search"}},"outcome_weights":{"good":20,"normal":50,"nothing":25,"failure":5,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.0,"wait":1.5,"stone":0.9},"failure":{"search":0.5,"wait":0.7,"stone":1.2}},"base_rare_rate":0.01,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨水沖淡氣味，更難辨別。"},"night":{"text_addon":"夜色遮掩，靈識更為重要。"}}}},
  {"base_type":"unknown","sub_types":["resource","nothing"],"tier":1,"attribute":"water","hidden_level":15,"total_layers":1,"progression":{"L1":{"text":"溪邊石縫滲出淡藍光澤，與尋常泉水不同。","best_action":"stone"}},"outcome_weights":{"good":20,"normal":50,"nothing":25,"failure":5,"worst_result":"failure"},"action_modifiers":{"good":{"search":1.8,"wait":1.2,"stone":2.0},"failure":{"search":0.6,"wait":0.9,"stone":0.4}},"base_rare_rate":0.01,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨天水靈氣更旺盛。"},"night":{"text_addon":"月色令水光更為明亮。"}}}},
  {"base_type":"unknown","sub_types":["monster","nothing","opportunity"],"tier":1,"attribute":"fire","hidden_level":18,"total_layers":3,"progression":{"L1":{"text":"前方地面溫熱，腳下石板微微發燙。","best_action":"wait"},"L2":{"text":"空氣中漂浮細小火星，偶爾閃滅。","best_action":"wait"},"L3":{"text":"靈氣在某處劇烈匯聚，波動如心跳。","best_action":"search"}},"outcome_weights":{"good":20,"normal":50,"nothing":25,"failure":5,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.2,"wait":1.3,"stone":0.8},"failure":{"search":0.4,"wait":0.6,"stone":1.3}},"base_rare_rate":0.01,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"大雨令火氣萎縮減弱。"},"night":{"text_addon":"黑夜中火光格外醒目。"}}}},
  {"base_type":"unknown","sub_types":["resource","nothing"],"tier":1,"attribute":"earth","hidden_level":10,"total_layers":2,"progression":{"L1":{"text":"土壤顏色較周遭深沉，質地異常鬆軟。","best_action":"wait"},"L2":{"text":"挖開表層，有淡淡靈氣從土中逸散。","best_action":"search"}},"outcome_weights":{"good":20,"normal":50,"nothing":25,"failure":5,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.0,"wait":1.4,"stone":1.0},"failure":{"search":0.5,"wait":0.7,"stone":1.0}},"base_rare_rate":0.01,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨後土壤靈氣更易感應。"},"night":{"text_addon":"夜間地氣上升，感應更清晰。"}}}},
  {"base_type":"unknown","sub_types":["monster","resource","nothing"],"tier":1,"attribute":"metal","hidden_level":22,"total_layers":2,"progression":{"L1":{"text":"岩壁上有細微刮痕，整齊如刀割。","best_action":"wait"},"L2":{"text":"金屬氣息隨風飄來，若有若無。","best_action":"search"}},"outcome_weights":{"good":20,"normal":50,"nothing":25,"failure":5,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.1,"wait":1.5,"stone":0.9},"failure":{"search":0.5,"wait":0.6,"stone":1.2}},"base_rare_rate":0.01,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"金氣在濕潤中更為內斂。"},"night":{"text_addon":"月光下金屬反光若隱若現。"}}}},
  {"base_type":"unknown","sub_types":["resource","nothing"],"tier":1,"attribute":"wood","hidden_level":8,"total_layers":1,"progression":{"L1":{"text":"老樹根部有淡綠光暈，隨風輕輕搖曳。","best_action":"search"}},"outcome_weights":{"good":20,"normal":50,"nothing":25,"failure":5,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.3,"wait":1.1,"stone":0.8},"failure":{"search":0.4,"wait":0.8,"stone":1.1}},"base_rare_rate":0.01,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨水滋潤，木靈氣更為充沛。"},"night":{"text_addon":"夜間光暈更加明顯清晰。"}}}},
  {"base_type":"unknown","sub_types":["monster","nothing"],"tier":1,"attribute":"water","hidden_level":20,"total_layers":3,"progression":{"L1":{"text":"水面波紋異常，並非風所引起。","best_action":"wait"},"L2":{"text":"水中有陰影緩慢移動，深不可測。","best_action":"wait"},"L3":{"text":"水底靈氣聚集，形成旋渦狀流動。","best_action":"stone"}},"outcome_weights":{"good":20,"normal":50,"nothing":25,"failure":5,"worst_result":"failure"},"action_modifiers":{"good":{"search":1.9,"wait":1.6,"stone":2.0},"failure":{"search":0.6,"wait":0.4,"stone":0.5}},"base_rare_rate":0.01,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨天水面更難觀察異常。"},"night":{"text_addon":"月光映水，陰影更為明顯。"}}}},
  {"base_type":"unknown","sub_types":["resource","opportunity","nothing"],"tier":1,"attribute":"fire","hidden_level":14,"total_layers":2,"progression":{"L1":{"text":"廢棄石屋殘垣，磚縫間有熱氣滲出。","best_action":"wait"},"L2":{"text":"靈氣殘留痕跡明顯，曾有修士在此煉丹。","best_action":"search"}},"outcome_weights":{"good":20,"normal":50,"nothing":25,"failure":5,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.2,"wait":1.3,"stone":0.9},"failure":{"search":0.5,"wait":0.7,"stone":1.1}},"base_rare_rate":0.01,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨水令殘留靈氣更快消散。"},"night":{"text_addon":"黑夜中熱氣更易察覺。"}}}},
  {"base_type":"unknown","sub_types":["monster","resource","nothing"],"tier":1,"attribute":"earth","hidden_level":17,"total_layers":2,"progression":{"L1":{"text":"山壁裂縫深處有黃色光點閃爍。","best_action":"wait"},"L2":{"text":"靠近後感受到土屬靈氣微弱流動。","best_action":"stone"}},"outcome_weights":{"good":20,"normal":50,"nothing":25,"failure":5,"worst_result":"failure"},"action_modifiers":{"good":{"search":1.8,"wait":1.4,"stone":2.1},"failure":{"search":0.6,"wait":0.7,"stone":0.4}},"base_rare_rate":0.01,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨後土壁更顯潮濕沉重。"},"night":{"text_addon":"夜間黃光在黑暗中更醒目。"}}}},
  {"base_type":"unknown","sub_types":["resource","nothing"],"tier":1,"attribute":"metal","hidden_level":11,"total_layers":1,"progression":{"L1":{"text":"荒地中露出角落，質地與周遭岩石不同。","best_action":"search"}},"outcome_weights":{"good":20,"normal":50,"nothing":25,"failure":5,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.4,"wait":1.0,"stone":0.9},"failure":{"search":0.4,"wait":0.9,"stone":1.0}},"base_rare_rate":0.01,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨水沖刷令礦石更清晰。"},"night":{"text_addon":"月光下金屬質地更為明顯。"}}}},
  {"base_type":"unknown","sub_types":["monster","resource","nothing"],"tier":2,"attribute":"wood","hidden_level":32,"total_layers":3,"progression":{"L1":{"text":"密林深處樹木搖晃，並無風吹。","best_action":"wait"},"L2":{"text":"葉片邊緣有細小靈紋，隨氣流變化。","best_action":"wait"},"L3":{"text":"木屬靈氣在某棵古樹周圍異常濃郁。","best_action":"search"}},"outcome_weights":{"good":22,"normal":45,"nothing":23,"failure":10,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.1,"wait":1.5,"stone":0.9},"failure":{"search":0.5,"wait":0.6,"stone":1.2}},"base_rare_rate":0.03,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨中木靈更為活躍。"},"night":{"text_addon":"夜間古樹靈氣外溢明顯。"}}}},
  {"base_type":"unknown","sub_types":["resource","opportunity","nothing"],"tier":2,"attribute":"water","hidden_level":38,"total_layers":4,"progression":{"L1":{"text":"山澗轉彎處水色異常，帶藍紫光澤。","best_action":"wait"},"L2":{"text":"水流方向與地勢不符，似有暗流引導。","best_action":"stone"},"L3":{"text":"水底靈氣形成渦旋，指向某個方向。","best_action":"search"},"L4":{"text":"渦旋中心有凝固靈氣結晶，靜待採取。","best_action":"search"}},"outcome_weights":{"good":22,"normal":45,"nothing":23,"failure":10,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.3,"wait":1.2,"stone":1.8},"failure":{"search":0.4,"wait":0.7,"stone":0.5}},"base_rare_rate":0.03,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨天水靈結晶更為活躍。"},"night":{"text_addon":"月色令水底結晶發光。"}}}},
  {"base_type":"unknown","sub_types":["monster","nothing","opportunity"],"tier":2,"attribute":"fire","hidden_level":35,"total_layers":3,"progression":{"L1":{"text":"乾涸河床上有焦黑圓形痕跡，疑似戰場。","best_action":"wait"},"L2":{"text":"空氣中殘留燃燒靈氣，尚未完全消散。","best_action":"wait"},"L3":{"text":"焦痕中心溫度仍高，有東西在此棲息。","best_action":"stone"}},"outcome_weights":{"good":22,"normal":45,"nothing":23,"failure":10,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.0,"wait":1.4,"stone":1.9},"failure":{"search":0.5,"wait":0.6,"stone":0.5}},"base_rare_rate":0.03,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"大雨令殘留火氣迅速消散。"},"night":{"text_addon":"夜間焦痕中心的熱度更易感知。"}}}},
  {"base_type":"unknown","sub_types":["resource","nothing"],"tier":2,"attribute":"earth","hidden_level":42,"total_layers":2,"progression":{"L1":{"text":"黃土高坡邊緣有細小晶體露出地表。","best_action":"wait"},"L2":{"text":"晶體排列規律，似乎是自然形成的靈脈。","best_action":"search"}},"outcome_weights":{"good":22,"normal":45,"nothing":23,"failure":10,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.2,"wait":1.4,"stone":0.9},"failure":{"search":0.5,"wait":0.7,"stone":1.1}},"base_rare_rate":0.03,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨後晶體更加閃耀明亮。"},"night":{"text_addon":"夜間地靈晶體散發微光。"}}}},
  {"base_type":"unknown","sub_types":["monster","resource","nothing"],"tier":2,"attribute":"metal","hidden_level":28,"total_layers":4,"progression":{"L1":{"text":"廢棄礦洞入口有金屬摩擦聲傳出。","best_action":"wait"},"L2":{"text":"洞內金屬氣息濃厚，夾雜腥甜氣味。","best_action":"stone"},"L3":{"text":"靈氣波動不規律，有兩種不同頻率交疊。","best_action":"stone"},"L4":{"text":"洞壁嵌有未開採的靈礦，旁有守護之物。","best_action":"search"}},"outcome_weights":{"good":22,"normal":45,"nothing":23,"failure":10,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.0,"wait":1.3,"stone":2.2},"failure":{"search":0.5,"wait":0.7,"stone":0.4}},"base_rare_rate":0.03,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨水流入礦洞，聲音更為複雜。"},"night":{"text_addon":"夜間礦洞更加幽深難測。"}}}},
  {"base_type":"unknown","sub_types":["resource","opportunity","nothing"],"tier":2,"attribute":"wood","hidden_level":30,"total_layers":3,"progression":{"L1":{"text":"枯萎植被中有一株異常翠綠，格格不入。","best_action":"wait"},"L2":{"text":"靠近後感覺到木靈氣從其根部湧出。","best_action":"stone"},"L3":{"text":"植株葉脈中有靈紋流動，正值靈氣旺盛期。","best_action":"search"}},"outcome_weights":{"good":22,"normal":45,"nothing":23,"failure":10,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.3,"wait":1.2,"stone":1.7},"failure":{"search":0.4,"wait":0.7,"stone":0.5}},"base_rare_rate":0.03,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨水令木靈草更為舒展。"},"night":{"text_addon":"夜間靈紋發光，一目了然。"}}}},
  {"base_type":"unknown","sub_types":["monster","nothing"],"tier":2,"attribute":"water","hidden_level":36,"total_layers":3,"progression":{"L1":{"text":"湖面中央有漣漪由內而外擴散，異於常態。","best_action":"wait"},"L2":{"text":"水溫較周遭低數度，有冷流從深處上湧。","best_action":"wait"},"L3":{"text":"水中靈氣集中於某點，感覺有生命在等待。","best_action":"stone"}},"outcome_weights":{"good":22,"normal":45,"nothing":23,"failure":10,"worst_result":"failure"},"action_modifiers":{"good":{"search":1.8,"wait":1.7,"stone":2.0},"failure":{"search":0.6,"wait":0.4,"stone":0.5}},"base_rare_rate":0.03,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨天水面波紋更難判讀。"},"night":{"text_addon":"月光映照，水中陰影更清晰。"}}}},
  {"base_type":"unknown","sub_types":["resource","nothing","opportunity"],"tier":2,"attribute":"fire","hidden_level":40,"total_layers":4,"progression":{"L1":{"text":"火山岩地帶地面持續散熱，不尋常。","best_action":"wait"},"L2":{"text":"裂縫中有橙紅光芒一閃而過。","best_action":"wait"},"L3":{"text":"火屬靈氣在裂縫深處濃烈匯聚。","best_action":"stone"},"L4":{"text":"裂縫底部有火靈石半露出岩層。","best_action":"search"}},"outcome_weights":{"good":22,"normal":45,"nothing":23,"failure":10,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.2,"wait":1.3,"stone":1.8},"failure":{"search":0.5,"wait":0.7,"stone":0.4}},"base_rare_rate":0.03,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"大雨落入裂縫，蒸汽騰起。"},"night":{"text_addon":"黑夜中橙紅光芒更為明顯。"}}}},
  {"base_type":"unknown","sub_types":["monster","resource","nothing"],"tier":2,"attribute":"earth","hidden_level":33,"total_layers":3,"progression":{"L1":{"text":"黃土平原上有一處土色明顯不同。","best_action":"wait"},"L2":{"text":"土屬靈氣從地下緩慢向上滲透。","best_action":"stone"},"L3":{"text":"地下有空洞，頂部岩石因靈氣而鬆動。","best_action":"search"}},"outcome_weights":{"good":22,"normal":45,"nothing":23,"failure":10,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.1,"wait":1.4,"stone":1.9},"failure":{"search":0.5,"wait":0.7,"stone":0.4}},"base_rare_rate":0.03,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨水滲入，地下空洞更顯潮濕。"},"night":{"text_addon":"夜間地氣外溢，靈感更強。"}}}},
  {"base_type":"unknown","sub_types":["monster","nothing"],"tier":2,"attribute":"metal","hidden_level":37,"total_layers":3,"progression":{"L1":{"text":"鐵鏽味濃厚，超過廢棄金屬應有程度。","best_action":"wait"},"L2":{"text":"金屬碎片周圍有靈氣殘留，似曾是法器。","best_action":"stone"},"L3":{"text":"其中一塊碎片仍在緩慢震動，靈氣未散。","best_action":"search"}},"outcome_weights":{"good":22,"normal":45,"nothing":23,"failure":10,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.2,"wait":1.3,"stone":1.8},"failure":{"search":0.5,"wait":0.6,"stone":0.5}},"base_rare_rate":0.03,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨水加速金屬腐蝕，異味更濃。"},"night":{"text_addon":"夜間震動的碎片隱約發光。"}}}},
  {"base_type":"unknown","sub_types":["monster","resource","nothing","opportunity"],"tier":3,"attribute":"fire","hidden_level":58,"total_layers":4,"progression":{"L1":{"text":"荒原上空氣乾燥灼熱，超過季節正常值。","best_action":"wait"},"L2":{"text":"地平線處有熱浪扭曲，靈氣流動異常。","best_action":"wait"},"L3":{"text":"火屬靈氣形成漩渦，中心有兩種氣息。","best_action":"stone"},"L4":{"text":"一動一靜：靜是火靈草，動是守護者。","best_action":"search"}},"outcome_weights":{"good":25,"normal":40,"nothing":20,"failure":15,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.4,"wait":1.2,"stone":1.8},"failure":{"search":0.4,"wait":0.6,"stone":0.5}},"base_rare_rate":0.08,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"大雨令火靈漩渦暫時減弱。"},"night":{"text_addon":"黑夜中火靈光芒更為耀眼。"}}}},
  {"base_type":"unknown","sub_types":["resource","opportunity","nothing"],"tier":3,"attribute":"water","hidden_level":62,"total_layers":5,"progression":{"L1":{"text":"深山瀑布旁霧氣異常濃厚，視線受阻。","best_action":"wait"},"L2":{"text":"霧中有藍光若隱若現，節律規律。","best_action":"wait"},"L3":{"text":"藍光來源是瀑布後方石壁，有靈紋刻痕。","best_action":"stone"},"L4":{"text":"靈紋呈陣法形態，似乎封印著某物。","best_action":"search"},"L5":{"text":"封印內有水靈核，乃上古修士所藏。","best_action":"search"}},"outcome_weights":{"good":25,"normal":40,"nothing":20,"failure":15,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.5,"wait":1.1,"stone":1.9},"failure":{"search":0.3,"wait":0.6,"stone":0.5}},"base_rare_rate":0.08,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨天霧氣更厚，視線更差。"},"night":{"text_addon":"夜間藍光在霧中如鬼火飄蕩。"}}}},
  {"base_type":"unknown","sub_types":["monster","nothing"],"tier":3,"attribute":"wood","hidden_level":55,"total_layers":4,"progression":{"L1":{"text":"古林中樹木排列整齊，非自然生長。","best_action":"wait"},"L2":{"text":"林間有木屬靈氣的「心跳」感，週期穩定。","best_action":"wait"},"L3":{"text":"心跳源自一棵千年古樹，樹幹有靈竅。","best_action":"stone"},"L4":{"text":"靈竅開合之間有靈蟲棲居，具攻擊性。","best_action":"search"}},"outcome_weights":{"good":25,"normal":40,"nothing":20,"failure":15,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.2,"wait":1.3,"stone":1.7},"failure":{"search":0.5,"wait":0.6,"stone":0.4}},"base_rare_rate":0.08,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨天木靈心跳節律加快。"},"night":{"text_addon":"夜間靈竅開合更加頻繁。"}}}},
  {"base_type":"unknown","sub_types":["resource","nothing","opportunity"],"tier":3,"attribute":"earth","hidden_level":68,"total_layers":5,"progression":{"L1":{"text":"黃土台地邊緣有不明隆起，規律排列。","best_action":"wait"},"L2":{"text":"靠近後感覺土屬靈氣由下而上涌動。","best_action":"wait"},"L3":{"text":"隆起處是埋藏的靈石原礦，尚未開採。","best_action":"stone"},"L4":{"text":"礦脈延伸範圍廣，但部分已被動過。","best_action":"search"},"L5":{"text":"礦脈核心有品質最高的一塊，完整未損。","best_action":"search"}},"outcome_weights":{"good":25,"normal":40,"nothing":20,"failure":15,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.4,"wait":1.1,"stone":1.9},"failure":{"search":0.4,"wait":0.7,"stone":0.4}},"base_rare_rate":0.08,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨後地脈靈氣更易感知。"},"night":{"text_addon":"夜間靈石原礦散發土黃微光。"}}}},
  {"base_type":"unknown","sub_types":["monster","resource","nothing"],"tier":3,"attribute":"metal","hidden_level":60,"total_layers":4,"progression":{"L1":{"text":"峭壁上有刀痕，深入岩石三寸有餘。","best_action":"wait"},"L2":{"text":"金屬靈氣殘留於刀痕中，尚未消散。","best_action":"stone"},"L3":{"text":"刀痕深處嵌有金屬殘片，帶法器痕跡。","best_action":"stone"},"L4":{"text":"殘片附近有靈獸來回巡視，守護領地。","best_action":"search"}},"outcome_weights":{"good":25,"normal":40,"nothing":20,"failure":15,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.3,"wait":1.2,"stone":2.0},"failure":{"search":0.4,"wait":0.7,"stone":0.4}},"base_rare_rate":0.08,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨水沖刷刀痕，靈氣加速消散。"},"night":{"text_addon":"夜間金屬殘片隱約反光。"}}}},
  {"base_type":"unknown","sub_types":["opportunity","nothing","monster"],"tier":3,"attribute":"fire","hidden_level":52,"total_layers":3,"progression":{"L1":{"text":"廢棄煉丹爐旁有殘火未滅，三日有餘。","best_action":"wait"},"L2":{"text":"丹爐殘留丹香，品質遠超普通丹藥。","best_action":"stone"},"L3":{"text":"爐底有未取出的失敗丹藥，仍有藥效。","best_action":"search"}},"outcome_weights":{"good":25,"normal":40,"nothing":20,"failure":15,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.3,"wait":1.2,"stone":1.8},"failure":{"search":0.4,"wait":0.7,"stone":0.5}},"base_rare_rate":0.08,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨水令殘火搖曳，更顯危險。"},"night":{"text_addon":"黑夜中殘火在黑暗中分外顯眼。"}}}},
  {"base_type":"unknown","sub_types":["resource","monster","nothing"],"tier":3,"attribute":"water","hidden_level":65,"total_layers":4,"progression":{"L1":{"text":"深谷底部有霧氣凝聚，不隨風消散。","best_action":"wait"},"L2":{"text":"霧中有水屬靈氣旋轉，形成小型渦流。","best_action":"wait"},"L3":{"text":"渦流中心有什麼東西在緩慢旋轉。","best_action":"stone"},"L4":{"text":"水靈珠半懸於渦流核心，旁有靈蛟盤繞。","best_action":"search"}},"outcome_weights":{"good":25,"normal":40,"nothing":20,"failure":15,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.2,"wait":1.3,"stone":1.9},"failure":{"search":0.4,"wait":0.6,"stone":0.4}},"base_rare_rate":0.08,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨天渦流更加猛烈難以接近。"},"night":{"text_addon":"月光照入谷底，靈珠熠熠生輝。"}}}},
  {"base_type":"unknown","sub_types":["monster","nothing","opportunity"],"tier":3,"attribute":"wood","hidden_level":57,"total_layers":5,"progression":{"L1":{"text":"藥谷入口有奇異香氣，令人精神一振。","best_action":"wait"},"L2":{"text":"香氣濃淡有節律，似有生命在吐納。","best_action":"wait"},"L3":{"text":"香氣源頭是谷底一棵靈藥樹，樹齡極長。","best_action":"stone"},"L4":{"text":"靈藥樹周圍有結界痕跡，已有人捷足先登。","best_action":"search"},"L5":{"text":"結界破損處有妖獸蟄伏，守護靈藥。","best_action":"search"}},"outcome_weights":{"good":25,"normal":40,"nothing":20,"failure":15,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.4,"wait":1.1,"stone":1.8},"failure":{"search":0.3,"wait":0.6,"stone":0.5}},"base_rare_rate":0.08,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨天香氣更加濃郁難以掩蓋。"},"night":{"text_addon":"夜間靈藥樹散發幽綠光芒。"}}}},
  {"base_type":"unknown","sub_types":["resource","nothing"],"tier":3,"attribute":"earth","hidden_level":70,"total_layers":3,"progression":{"L1":{"text":"砂礫地帶有幾塊石頭排列特殊，似有深意。","best_action":"wait"},"L2":{"text":"石頭下方土壤靈氣異常濃厚，向上滲透。","best_action":"stone"},"L3":{"text":"掀開石頭，下方有靈土一層，質地細膩。","best_action":"search"}},"outcome_weights":{"good":25,"normal":40,"nothing":20,"failure":15,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.2,"wait":1.3,"stone":1.8},"failure":{"search":0.5,"wait":0.7,"stone":0.4}},"base_rare_rate":0.08,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨水令靈土氣息更加明顯。"},"night":{"text_addon":"夜間靈土散發淡淡土黃光芒。"}}}},
  {"base_type":"unknown","sub_types":["monster","resource","nothing"],"tier":3,"attribute":"metal","hidden_level":63,"total_layers":4,"progression":{"L1":{"text":"礦場舊址有金屬撞擊聲，但礦場已廢棄多年。","best_action":"wait"},"L2":{"text":"金屬靈氣異常活躍，比開採時期更為濃郁。","best_action":"wait"},"L3":{"text":"廢棄礦井底部有新的礦脈自然形成。","best_action":"stone"},"L4":{"text":"礦脈旁有金屬妖獸棲居，以靈礦為食。","best_action":"search"}},"outcome_weights":{"good":25,"normal":40,"nothing":20,"failure":15,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.3,"wait":1.2,"stone":1.9},"failure":{"search":0.4,"wait":0.6,"stone":0.4}},"base_rare_rate":0.08,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨水流入礦井，聲音更為雜亂。"},"night":{"text_addon":"夜間礦脈隱約透出金屬光澤。"}}}},
  {"base_type":"unknown","sub_types":["opportunity","nothing","monster"],"tier":3,"attribute":"water","hidden_level":59,"total_layers":4,"progression":{"L1":{"text":"古橋下流水顏色深藍，非正常水色。","best_action":"wait"},"L2":{"text":"橋墩附近有靈氣殘留，似曾有陣法。","best_action":"stone"},"L3":{"text":"水中隱約可見陣法基底，尚有少許靈力。","best_action":"stone"},"L4":{"text":"陣法殘留中封印有水屬功法殘頁一張。","best_action":"search"}},"outcome_weights":{"good":25,"normal":40,"nothing":20,"failure":15,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.4,"wait":1.2,"stone":2.1},"failure":{"search":0.4,"wait":0.6,"stone":0.4}},"base_rare_rate":0.08,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨水令陣法殘留加速消散。"},"night":{"text_addon":"月光照水，陣法紋路更清晰。"}}}},
  {"base_type":"unknown","sub_types":["monster","resource","nothing","opportunity"],"tier":4,"attribute":"fire","hidden_level":78,"total_layers":5,"progression":{"L1":{"text":"火山噴氣孔群中，有一孔氣色異常純淨。","best_action":"wait"},"L2":{"text":"純淨氣孔周遭溫度比其他孔低，自相矛盾。","best_action":"wait"},"L3":{"text":"火屬靈氣在此凝而不散，呈固態雛形。","best_action":"stone"},"L4":{"text":"凝固靈氣中有生命跡象，正在誕生。","best_action":"search"},"L5":{"text":"火靈珠初成，旁有火鳳幼雛護衛。","best_action":"search"}},"outcome_weights":{"good":28,"normal":35,"nothing":17,"failure":20,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.5,"wait":1.1,"stone":1.9},"failure":{"search":0.3,"wait":0.5,"stone":0.4}},"base_rare_rate":0.15,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"大雨與火靈形成劇烈對抗。"},"night":{"text_addon":"黑夜中火靈珠光芒普照四方。"}}}},
  {"base_type":"unknown","sub_types":["resource","opportunity","nothing"],"tier":4,"attribute":"water","hidden_level":82,"total_layers":6,"progression":{"L1":{"text":"深海崖壁附近水壓異常，向上湧而非向下。","best_action":"wait"},"L2":{"text":"逆流源頭在崖壁裂縫，隱隱有藍光透出。","best_action":"wait"},"L3":{"text":"裂縫深處有上古時代的靈泉封印。","best_action":"stone"},"L4":{"text":"封印由五行陣法構成，水系已近自然解除。","best_action":"stone"},"L5":{"text":"陣法節點明確，有效破解需從西北角起始。","best_action":"search"},"L6":{"text":"靈泉核心有水系天材，萬年難得一見。","best_action":"search"}},"outcome_weights":{"good":28,"normal":35,"nothing":17,"failure":20,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.5,"wait":1.0,"stone":2.2},"failure":{"search":0.3,"wait":0.5,"stone":0.3}},"base_rare_rate":0.15,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨天逆流更強，近身更危險。"},"night":{"text_addon":"月升時封印自動弱化一刻鐘。"}}}},
  {"base_type":"unknown","sub_types":["monster","nothing","opportunity"],"tier":4,"attribute":"wood","hidden_level":86,"total_layers":5,"progression":{"L1":{"text":"萬年古木林中心有樹木枯萎，形成圓形空地。","best_action":"wait"},"L2":{"text":"枯萎並非病害，而是靈氣被某物吸盡。","best_action":"wait"},"L3":{"text":"空地中心有地下靈根，正在開花結果。","best_action":"stone"},"L4":{"text":"靈根開花時散發幻術，令靠近者迷失方向。","best_action":"search"},"L5":{"text":"靈根外有木系大妖鎮守，化形已達七成。","best_action":"search"}},"outcome_weights":{"good":28,"normal":35,"nothing":17,"failure":20,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.4,"wait":1.1,"stone":1.8},"failure":{"search":0.3,"wait":0.5,"stone":0.4}},"base_rare_rate":0.15,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨天幻術因水氣干擾而減弱。"},"night":{"text_addon":"夜間靈根花朵完全綻放，最為美麗。"}}}},
  {"base_type":"unknown","sub_types":["resource","monster","nothing"],"tier":4,"attribute":"earth","hidden_level":90,"total_layers":5,"progression":{"L1":{"text":"地震後新露出的斷層，岩層排列奇特。","best_action":"wait"},"L2":{"text":"斷層面有靈脈橫截面，千年積累可見。","best_action":"wait"},"L3":{"text":"靈脈品質遠超普通，達到天地靈脈等級。","best_action":"stone"},"L4":{"text":"靈脈中有土屬寶物結晶，正在自然成形。","best_action":"search"},"L5":{"text":"寶物周圍有土系靈蟲群聚，數量驚人。","best_action":"search"}},"outcome_weights":{"good":28,"normal":35,"nothing":17,"failure":20,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.5,"wait":1.0,"stone":1.9},"failure":{"search":0.3,"wait":0.6,"stone":0.4}},"base_rare_rate":0.15,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨後斷層更加不穩，需格外小心。"},"night":{"text_addon":"夜間靈脈截面散發明亮土黃光芒。"}}}},
  {"base_type":"unknown","sub_types":["monster","opportunity","nothing"],"tier":4,"attribute":"metal","hidden_level":88,"total_layers":6,"progression":{"L1":{"text":"廢棄鑄器場有金屬鳴嘯，清脆而尖銳。","best_action":"wait"},"L2":{"text":"鳴嘯來自場中央一塊漂浮的金屬碎片。","best_action":"wait"},"L3":{"text":"碎片是上古法器殘骸，仍帶器靈意志。","best_action":"stone"},"L4":{"text":"器靈殘留意識在試探靠近者的修為。","best_action":"stone"},"L5":{"text":"通過考驗者可獲得器靈認可，反之遭攻擊。","best_action":"search"},"L6":{"text":"器靈核心藏有上古鑄器法門，價值連城。","best_action":"search"}},"outcome_weights":{"good":28,"normal":35,"nothing":17,"failure":20,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.5,"wait":1.0,"stone":2.2},"failure":{"search":0.3,"wait":0.5,"stone":0.3}},"base_rare_rate":0.15,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨天金屬鳴嘯更加淒厲尖銳。"},"night":{"text_addon":"夜間漂浮碎片發出幽藍金屬光。"}}}},
  {"base_type":"unknown","sub_types":["opportunity","monster","nothing"],"tier":4,"attribute":"fire","hidden_level":80,"total_layers":4,"progression":{"L1":{"text":"荒漠中有一座小型火陣，無人布置卻自行運轉。","best_action":"wait"},"L2":{"text":"火陣節點有靈氣自動補充，來源不明。","best_action":"stone"},"L3":{"text":"陣法核心連接地下火靈脈，自給自足。","best_action":"stone"},"L4":{"text":"進入陣法可借火靈脈之力修煉，但有守陣之物。","best_action":"search"}},"outcome_weights":{"good":28,"normal":35,"nothing":17,"failure":20,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.3,"wait":1.1,"stone":2.1},"failure":{"search":0.3,"wait":0.6,"stone":0.4}},"base_rare_rate":0.15,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"大雨令火陣節點暫時紊亂。"},"night":{"text_addon":"夜間火陣光芒映照半空。"}}}},
  {"base_type":"unknown","sub_types":["resource","nothing","monster"],"tier":4,"attribute":"water","hidden_level":85,"total_layers":5,"progression":{"L1":{"text":"冰原裂縫中有液態靈水，不因寒冷而凍結。","best_action":"wait"},"L2":{"text":"靈水隨裂縫延伸至深處，深不見底。","best_action":"wait"},"L3":{"text":"靈水中有微小晶體漂浮，屬高階靈材。","best_action":"stone"},"L4":{"text":"晶體聚集處有水脈源頭，被冰靈獸守護。","best_action":"search"},"L5":{"text":"冰靈獸處於冬眠，但外力可能喚醒。","best_action":"search"}},"outcome_weights":{"good":28,"normal":35,"nothing":17,"failure":20,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.2,"wait":1.2,"stone":1.9},"failure":{"search":0.4,"wait":0.5,"stone":0.4}},"base_rare_rate":0.15,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨落冰原，裂縫靈水泛起漣漪。"},"night":{"text_addon":"夜間靈水在月光下閃爍如星。"}}}},
  {"base_type":"unknown","sub_types":["monster","resource","nothing","opportunity"],"tier":4,"attribute":"wood","hidden_level":92,"total_layers":6,"progression":{"L1":{"text":"靈藥山脈深處有植被集體倒伏，指向一方。","best_action":"wait"},"L2":{"text":"倒伏方向有強烈木靈氣波動，週期性出現。","best_action":"wait"},"L3":{"text":"波動源自一棵萬年靈木，正在結靈果。","best_action":"stone"},"L4":{"text":"靈果結成時散發的氣息吸引四方妖獸。","best_action":"stone"},"L5":{"text":"靈果成熟度已達九成，再等半刻即完全熟透。","best_action":"search"},"L6":{"text":"摘取最佳時機在靈木吐納之間的瞬息空隙。","best_action":"search"}},"outcome_weights":{"good":28,"normal":35,"nothing":17,"failure":20,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.5,"wait":1.0,"stone":1.8},"failure":{"search":0.3,"wait":0.5,"stone":0.4}},"base_rare_rate":0.15,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨天靈果成熟被加速，時機更緊迫。"},"night":{"text_addon":"月夜靈木吐納更為深長，間隔延長。"}}}},
  {"base_type":"unknown","sub_types":["monster","resource","nothing","opportunity"],"tier":5,"attribute":"fire","hidden_level":105,"total_layers":6,"progression":{"L1":{"text":"天火隕落之地，火靈氣已達到自然極限。","best_action":"wait"},"L2":{"text":"地面火紋自行蔓延，非人力所為。","best_action":"wait"},"L3":{"text":"火紋匯聚處有天地靈氣凝結核心。","best_action":"stone"},"L4":{"text":"凝結核心是千年一遇的火靈結丹之地。","best_action":"stone"},"L5":{"text":"此地有天罰火焰環繞，誤入者必受灼傷。","best_action":"search"},"L6":{"text":"火焰有規律息滅，間隔九息，是唯一時機。","best_action":"search"}},"outcome_weights":{"good":30,"normal":25,"nothing":15,"failure":30,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.5,"wait":1.0,"stone":1.8},"failure":{"search":0.3,"wait":0.4,"stone":0.3}},"base_rare_rate":0.25,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"天降大雨與天火對抗，場面壯烈。"},"night":{"text_addon":"夜間天火映天，百里可見。"}}}},
  {"base_type":"unknown","sub_types":["resource","opportunity","monster","nothing"],"tier":5,"attribute":"water","hidden_level":98,"total_layers":6,"progression":{"L1":{"text":"萬年冰川底部有液態靈水區域，違反物理。","best_action":"wait"},"L2":{"text":"液態區靈氣濃度超出人體承受上限。","best_action":"wait"},"L3":{"text":"此地是上古海神祭壇遺址，水靈凝聚千年。","best_action":"stone"},"L4":{"text":"祭壇中心有水靈本源，天下水系盡皆臣服。","best_action":"stone"},"L5":{"text":"本源有意識，會判斷靠近者是否有資格。","best_action":"search"},"L6":{"text":"以誠心相對，不強取豪奪，方可得到認可。","best_action":"wait"}},"outcome_weights":{"good":30,"normal":25,"nothing":15,"failure":30,"worst_result":"failure"},"action_modifiers":{"good":{"search":1.8,"wait":2.5,"stone":1.0},"failure":{"search":0.4,"wait":0.3,"stone":0.5}},"base_rare_rate":0.25,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"天降靈雨令祭壇本源短暫復甦。"},"night":{"text_addon":"月神降臨之夜，祭壇光芒全開。"}}}},
  {"base_type":"unknown","sub_types":["opportunity","monster","nothing","resource"],"tier":5,"attribute":"wood","hidden_level":112,"total_layers":6,"progression":{"L1":{"text":"世界樹根系延伸至此，萬物皆得生機。","best_action":"wait"},"L2":{"text":"根系中流動的是木靈本源，濃到幾乎可見。","best_action":"wait"},"L3":{"text":"根系交匯點有木靈意志存在，非妖非仙。","best_action":"stone"},"L4":{"text":"木靈意志試探靠近者的心性，善惡皆有回應。","best_action":"stone"},"L5":{"text":"通過試探者可與木靈意志溝通，獲得饋贈。","best_action":"search"},"L6":{"text":"拒絕者或心性不純者將被根系驅逐，輕則重傷。","best_action":"search"}},"outcome_weights":{"good":30,"normal":25,"nothing":15,"failure":30,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.5,"wait":1.0,"stone":1.5},"failure":{"search":0.3,"wait":0.5,"stone":0.4}},"base_rare_rate":0.25,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"靈雨滋潤，木靈意志更加活躍。"},"night":{"text_addon":"夜間根系散發幽綠光芒，如夢似幻。"}}}},
  {"base_type":"unknown","sub_types":["monster","opportunity","nothing","resource"],"tier":5,"attribute":"earth","hidden_level":118,"total_layers":6,"progression":{"L1":{"text":"大地龍脈所在，腳下土地有心跳之感。","best_action":"wait"},"L2":{"text":"龍脈心跳每十二個時辰一次，正值間隔。","best_action":"wait"},"L3":{"text":"龍脈核心有土屬至寶，待龍脈心跳時出世。","best_action":"stone"},"L4":{"text":"守護龍脈者是土龍真身，沉睡三千年。","best_action":"stone"},"L5":{"text":"土龍睡眠脆弱，任何動靜都可能喚醒。","best_action":"search"},"L6":{"text":"龍脈心跳間隙僅有三息，是唯一無風險時機。","best_action":"search"}},"outcome_weights":{"good":30,"normal":25,"nothing":15,"failure":30,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.5,"wait":1.0,"stone":1.7},"failure":{"search":0.3,"wait":0.4,"stone":0.3}},"base_rare_rate":0.25,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雨天大地潮濕，龍脈心跳更易感知。"},"night":{"text_addon":"月夜龍脈靈氣外溢，危機更甚。"}}}},
  {"base_type":"unknown","sub_types":["opportunity","resource","monster","nothing"],"tier":5,"attribute":"metal","hidden_level":108,"total_layers":6,"progression":{"L1":{"text":"天劍峰頂金屬靈氣達到臨界，空氣可傷人。","best_action":"wait"},"L2":{"text":"峰頂有上古劍修留下的劍意殘留，鋒銳至極。","best_action":"wait"},"L3":{"text":"劍意已凝固成形，化為無形之劍懸於空中。","best_action":"stone"},"L4":{"text":"劍意試圖尋找繼承者，斬殺不合格者。","best_action":"stone"},"L5":{"text":"劍心清明、殺意純粹者方可通過試煉。","best_action":"search"},"L6":{"text":"無形之劍的劍胚封存於峰頂岩石之中。","best_action":"search"}},"outcome_weights":{"good":30,"normal":25,"nothing":15,"failure":30,"worst_result":"failure"},"action_modifiers":{"good":{"search":2.5,"wait":1.0,"stone":1.8},"failure":{"search":0.3,"wait":0.4,"stone":0.3}},"base_rare_rate":0.25,"entity_data":{"environment_modifiers":{"rainy":{"text_addon":"雷雨天劍意更為狂暴難以接近。"},"night":{"text_addon":"夜間劍意化為光柱直衝雲霄。"}}}}
];

// ── Main ─────────────────────────────────────────────────────────
const client = new pg.Client({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});

await client.connect();

let success = 0;
let failures = [];

for (let i = 0; i < EVENTS.length; i++) {
  const ev = EVENTS[i];

  const err = validate(ev, i);
  if (err) {
    failures.push({ index: i + 1, reason: err });
    continue;
  }

  try {
    await client.query(
      `INSERT INTO events
         (base_type, sub_types, tier, attribute, hidden_level, total_layers,
          progression, outcome_weights, action_modifiers, base_rare_rate, entity_data)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,
      [
        ev.base_type,
        ev.sub_types ?? [],
        ev.tier,
        ev.attribute,
        ev.hidden_level,
        ev.total_layers,
        JSON.stringify(ev.progression),
        JSON.stringify(ev.outcome_weights),
        JSON.stringify(ev.action_modifiers),
        ev.base_rare_rate,
        JSON.stringify(ev.entity_data ?? {}),
      ]
    );
    success++;
  } catch (e) {
    failures.push({ index: i + 1, reason: e.message });
  }
}

await client.end();

console.log(`\n✅ 成功插入：${success} 條`);
if (failures.length > 0) {
  console.log(`❌ 失敗：${failures.length} 條`);
  failures.forEach(f => console.log(`   第 ${f.index} 條 — ${f.reason}`));
} else {
  console.log('所有事件驗證通過，無失敗。');
}
